### ISSUE TITLE
Some error comes, while installing packages

### ISSUE THREAD

**Issue by itzshubhamdev** [Luxxy-GF/Linux-Stats#1]
![Screenshot_20220506-204454_Termius](https://user-images.githubusercontent.com/88220606/167162208-a3405fdd-2c1f-4986-ade5-76901f91c604.jpg)
![Screenshot_20220506-204518_Termius](https://user-images.githubusercontent.com/88220606/167162216-3cfc0a37-84a6-4520-8456-e82959241854.jpg)
![Screenshot_20220506-204527_Termius](https://user-images.githubusercontent.com/88220606/167162221-ac5909bc-98d6-407b-a05e-b1317784f7e8.jpg)

The packages seems to be broken

**Comment by Luxxy-GF** [comment]
for linux you would need to install node 14 and do 

apt install gcc g++ make -y 

you might need to install python to 

let you know this old software it be better to use https://github.com/luxxy-hosting/Node-API
its the same as this script
